
[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1


framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.flash_mode = dio
board_build.f_flash = 80000000L
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    SPI
    Wire
    Adafruit Unified Sensor@^1.1.15
    Adafruit BusIO@1.17.4
    Adafruit SHTC3 Library@^1.0.2
    SensorLib@^0.4.0
    XPowersLib@^0.3.3
    GxEPD2@^1.6.8
